export const WORDS = 
[
  [
    'mitad', 
    'palma',
    'topar', 
    'gusto',
    'borde',
    'tomar',
    'bañar',
    'carta',
    'ceder',
    'rozar',
    'falla',
    'sucio',
    'chico',
    'poder',
    'sobra',
    'tocar',
    'éxito',
    'pobre',
    'lejos',
    'cupla',
    'gallo',
    'antes',
    'guapo',
    'curso',
    'arroz',
    'ácido',
    'justo'
  ],

  [
    'half, middle',
    'palm tree',
    'to run into, bump into',
    'pleasure, taste, preference',
    'edge',
    'to take, drink',
    'to bathe, take a bath',
    'letter, (playing) card',
    'to transfer, to give in',
    'to touch (lightly)',
    'flaw, failure',
    'dirty, filthy',
    'kid',
    'to be able to, power', 
    'excess, surplus, leftover',
    'to touch, play (instrument)',
    'success',
    'poor',
    'far away',
    'blame, fault',
    'rooster',
    'before',
    'handsome, beautiful',
    'course, direction',
    'rice',
    'acid',
    'fair, just'
  ]
]